document.documentElement.classList.add('js');
const resume={
role:'Senior Art Director',
stats:[['250+','Clients.'],['12+','Years.'],['One','obsessive visual mind.']],
bio:"I'm an artist who found home in advertising, crafting campaigns that blur the lines between direction, digital art, and real-world storytelling. I play with light, shape ideas, and use AI to take creativity even further.",
portfolio:{label:'https://www.behance.net/muhammedrady3a',url:'https://www.behance.net/muhammedrady3a'},
skills:['Art direction','Visual storytelling','Concept development','Campaign ideation','Digital design','AI-powered visuals','Photo manipulation','Photography direction','Brand identity','Studio & shoot supervision','Team leadership','Moodboarding','Motion briefing','Retouching'],
clients:['BMW','Audi','Maserati','Volkswagen','Toyota','Honda','Kia','Geely','Samsung','Huawei','KFC','Nivea','Pirelli'],
journey:[['Senior Art Director','Fuse Integrated','Riyadh, Saudi Arabia','May 2024 - Present / Full-Time / Remote'],['Senior Art Director','FP7 McCann','Riyadh, Saudi Arabia','Aug 2024 - Sep 2024 / Freelance / Remote'],['Art Director','FP7 McCann','Riyadh, Saudi Arabia','Dec 2023 - May 2024 / Full-Time / Remote'],['Art Director','Acquaint Communications','Saudi Arabia','Jun 2023 - Dec 2023 / Full-Time / On-site Cairo Office'],['Visual Artist','Frepik','Spain','Mar 2022 - Sep 2024 / Freelance / Remote'],['Art Director','Icon Creations','Egypt','Mar 2022 - Jun 2023 / Full-Time / On-site'],['Senior Graphic Designer','','','Jun 2019 - Mar 2022 / Full-Time / On-site',true],['Graphic Designer','','','May 2017 - Jun 2019 / Full-Time / On-site',true]],
contact:[['@','muhammedrady3@gmail.com'],['+','+20125711638'],['•','Cairo, Egypt']]
};
function render(){document.querySelector('.role').textContent=resume.role;bio.textContent=resume.bio;portfolioUrl.textContent=resume.portfolio.label;behanceLink.href=resume.portfolio.url;stats.innerHTML=resume.stats.map(s=>`<div class="stat"><strong>${s[0]}</strong> <span>${s[1]}</span></div>`).join('');skillsList.innerHTML=resume.skills.map(s=>`<li>${s}</li>`).join('');clientsGrid.innerHTML=resume.clients.map(c=>`<span class="client">${c}</span>`).join('');timeline.innerHTML=resume.journey.map(i=>{const t=i[1]?`<span class="timeline-role">${i[0]}</span><br>${i[1]} - ${i[2]}`:i[0];return `<li class="${i[4]?'dot-item':''}"><h3>${t}</h3><p>${i[3]}</p></li>`}).join('');contactList.innerHTML=resume.contact.map(i=>`<li><span class="icon">${i[0]}</span><span>${i[1]}</span></li>`).join('')}
function reveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('is-visible'));return}const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');ob.unobserve(e.target)}}),{threshold:.16});items.forEach((i,n)=>{i.style.transitionDelay=Math.min(n*70,360)+'ms';ob.observe(i)})}
function parallax(){const t=document.querySelector('[data-parallax="title"]');if(!matchMedia('(min-width:769px)').matches||!matchMedia('(pointer:fine)').matches||matchMedia('(prefers-reduced-motion:reduce)').matches)return;addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;t.style.transform=`translate(${x*-10}px,${y*-7}px)`},{passive:true});addEventListener('scroll',()=>{t.style.opacity=.13-Math.min(scrollY/700,1)*.04},{passive:true})}
function glow(){const g=document.querySelector('.cursor-glow');if(!matchMedia('(pointer:fine)').matches)return;addEventListener('pointermove',e=>{g.style.opacity='1';g.style.transform=`translate(${e.clientX-130}px,${e.clientY-130}px)`},{passive:true});document.addEventListener('mouseleave',()=>g.style.opacity='0')}
render();reveal();parallax();glow();
